ChessTourManager.WEB/Controllers/TournamentsController.cs
using System.Security.Claims;
using ChessTourManager.DataAccess;
using ChessTourManager.DataAccess.Entities;
using ChessTourManager.DataAccess.Queries.Delete;
using ChessTourManager.DataAccess.Queries.Get;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ChessTourManager.WEB.Controllers;

/// <inheritdoc />
/// <summary>
/// The controller for the tournaments.
/// </summary>
public class TournamentsController : Controller
{
    private readonly ChessTourContext _context;
    private static   int?             _organizerId;

    /// <summary>
    /// The constructor of the controller.
    /// </summary>
    /// <param name="context">The context of the database.</param>
    public TournamentsController(ChessTourContext context)
    {
        this._context = context;
    }

    /// <summary>
    /// GET: Tournaments.
    /// </summary>
    /// <returns>The view of the tournaments.</returns>
    [Authorize]
    public async Task<IActionResult> Index(int? organizerId)
    {
        if (this.User.Identity?.IsAuthenticated ?? false)
        {
            _organizerId = this.User.FindFirstValue(ClaimTypes.NameIdentifier) is null
                               ? 0
                               : int.Parse(this.User.FindFirstValue(ClaimTypes.NameIdentifier)
                                        ?? throw new InvalidOperationException("User ID is null"));
        }
        else
        {
            _organizerId = organizerId ?? _organizerId;
        }

        GetResult result = IGetQueries.CreateInstance(this._context)
                                      .TryGetTournaments((int)_organizerId, out List<Tournament>? tournaments);
        if (result == GetResult.UserNotFound)
        {
            return this.NotFound();
        }

        await this.LoadKindsToViewBagAsync();
        await this.LoadSystemsToViewBagAsync();

        return this.View(tournaments);
    }

    /// <summary>
    /// GET: Tournaments/Create.
    /// </summary>
    /// <returns>The create view of the tournament.</returns>
    [Authorize]
    public async Task<IActionResult> Create()
    {
        await this.LoadSystemsToViewBagAsync();
        await this.LoadKindsToViewBagAsync();

        return this.View(new Tournament
                         {
                             OrganizerId = _organizerId
                                        ?? throw new InvalidOperationException("OrganizerId is null")
                         });
    }

    /// <summary>
    /// POST: Tournaments/Create.
    /// </summary>
    /// <param name="tournament">The tournament.</param>
    /// <returns>The index view of the tournaments.</returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize]
    public async Task<IActionResult> Create(Tournament tournament)
    {
        await this.LoadSystemsToViewBagAsync();
        await this.LoadKindsToViewBagAsync();

        if (!this.ModelState.IsValid)
        {
            return this.View(tournament);
        }

        await this._context.Tournaments.AddAsync(tournament);
        await this._context.SaveChangesAsync();

        if (this.TempData != null)
        {
            this.TempData["Success"] = $"Tournament {tournament.TournamentName} created successfully!";
        }

        return this.RedirectToAction(nameof(this.Index));
    }

    /// <summary>
    /// GET: Tournaments/Edit/{id}.
    /// </summary>
    /// <param name="id">The id of the tournament.</param>
    /// <returns>The edit view of the tournament.</returns>
    [Authorize]
    public async Task<IActionResult> Edit(int id)
    {
        await this.LoadKindsToViewBagAsync();
        await this.LoadSystemsToViewBagAsync();

        IGetQueries.CreateInstance(this._context)
                   .TryGetTournaments((int)_organizerId, out List<Tournament>? tournaments);
        Tournament? tournament = tournaments?.Find(t => t.Id == id && t.OrganizerId == _organizerId);

        if (tournament == null)
        {
            return this.NotFound();
        }

        return this.View(tournament);
    }

    /// <summary>
    /// POST: Tournaments/Edit/{id}.
    /// </summary>
    /// <param name="tournament">The tournament.</param>
    /// <returns>The index view of the tournaments.</returns>
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize]
    public async Task<IActionResult> Edit(Tournament tournament)
    {
        if (!this.ModelState.IsValid)
        {
            return this.View(tournament);
        }

        try
        {
            tournament.DateLastChange = DateOnly.FromDateTime(DateTime.Now);
            tournament.TimeLastChange = TimeOnly.FromDateTime(DateTime.Now);
            this._context.Tournaments.Update(tournament);
            await this._context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!await this.TournamentExists(tournament.Id))
            {
                return this.NotFound();
            }

            throw;
        }

        this.TempData["Success"] = $"Tournament {tournament.TournamentName} edited successfully!";
        return this.RedirectToAction(nameof(this.Index));
    }

    private async Task<bool> TournamentExists(int tournamentId)
    {
        return await this._context.Tournaments.AnyAsync(tournament =>
                                                            tournament             != null
                                                         && tournament.Id          == tournamentId
                                                         && tournament.OrganizerId == _organizerId);
    }

    /// <summary>
    /// GET: Tournaments/Details/{id}.
    /// </summary>
    /// <param name="id">The id of the tournament.</param>
    /// <returns>The details view of the tournament.</returns>
    [Authorize]
    public async Task<IActionResult> Details(int id)
    {
        await this.LoadKindsToViewBagAsync();
        await this.LoadSystemsToViewBagAsync();

        IGetQueries.CreateInstance(this._context)
                   .TryGetTournaments((int)_organizerId, out List<Tournament>? tournaments);
        Tournament? tournament = tournaments?.Find(t => t.Id == id && t.OrganizerId == _organizerId);

        if (tournament == null)
        {
            return this.NotFound();
        }

        return this.View(tournament);
    }

    /// <summary>
    /// GET: Tournaments/Delete/{id}.
    /// </summary>
    /// <param name="id">The id of the tournament.</param>
    /// <returns>The delete view of the tournament.</returns>
    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
        await this.LoadKindsToViewBagAsync();
        await this.LoadSystemsToViewBagAsync();

        IGetQueries.CreateInstance(this._context)
                   .TryGetTournaments((int)_organizerId, out List<Tournament>? tournaments);
        Tournament? tournament = tournaments?.Find(t => t.Id == id && t.OrganizerId == _organizerId);

        if (tournament == null)
        {
            return this.NotFound();
        }

        return this.View(tournament);
    }

    /// <summary>
    /// POST: Tournaments/Delete/{id}.
    /// </summary>
    /// <param name="id">The id of the tournament.</param>
    /// <returns>The index view of the tournaments.</returns>
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    [Authorize]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        IGetQueries.CreateInstance(this._context)
                   .TryGetTournaments((int)_organizerId, out List<Tournament>? tournaments);
        Tournament? tournament = tournaments?.Find(t => t.Id == id && t.OrganizerId == _organizerId);

        if (tournament == null)
        {
            return this.RedirectToAction(nameof(this.Index));
        }

        DeleteResult res = IDeleteQueries.CreateInstance(this._context)
                                         .TryDeleteTournament(tournament);

        if (res == DeleteResult.Success)
        {
            this.TempData["Success"] = $"Tournament {tournament.TournamentName} deleted successfully!";
        }
        else
        {
            this.TempData["Error"] = $"Tournament {tournament.TournamentName} could not be deleted!";
        }

        return this.RedirectToAction(nameof(this.Index));
    }

    private async Task LoadSystemsToViewBagAsync()
    {
        await Task.Run(() =>
                       {
                           IGetQueries.CreateInstance(this._context)
                                      .GetSystems(out List<DataAccess.Entities.System>? systems);

                           this.ViewBag.Systems = systems?.Select(s => new SelectListItem
                                                                       {
                                                                           Text  = s.SystemNameLocalized,
                                                                           Value = s.Id.ToString(),
                                                                       }) ?? Array.Empty<SelectListItem>();
                       });
    }

    private async Task LoadKindsToViewBagAsync()
    {
        await Task.Run(() =>
                       {
                           IGetQueries.CreateInstance(this._context)
                                      .GetKinds(out List<Kind>? kinds);

                           this.ViewBag.Kinds = kinds?.Select(s => new SelectListItem
                                                                   {
                                                                       Text  = s.KindNameLocalized,
                                                                       Value = s.Id.ToString(),
                                                                   }) ?? Array.Empty<SelectListItem>();
                       });
    }
}

ChessTourManager.WEB/Views/Shared/_DataTablePartial.cshtml
<p style="display: inline-block;">
    <button onclick="DownloadToExcel()" class="btn btn-primary">Download to Excel</button>
    <button onclick="Print()" class="btn btn-primary">Print</button>
</p>

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>

<script>function Print() {
var divToPrint = document.getElementById('table');
var htmlToPrint = '' +
    '<style type="text/css">' +
    'table th, table td {' +
    'border:1px solid #000;' +
    'padding;0.5em;' +
    '}' +
    '</style>';
htmlToPrint += divToPrint.outerHTML;
newWin = window.open("");
newWin.document.write(htmlToPrint);
newWin.print();
newWin.close();
}

function DownloadToExcel() {

var htmls = $("#table").html();
var uri = 'data:application/vnd.ms-excel;base64,';
var template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>';
var base64 = function (s) {
    return window.btoa(unescape(encodeURIComponent(s)))
};

var format = function (s, c) {
    return s.replace(/{(\w+)}/g, function (m, p) {
        return c[p];
    })
};

var ctx = {
    worksheet: "table",
    table: '<table>' + htmls + '</table>'
}

var compareLink = document.createElement("a");
compareLink.download = "table.xls";
compareLink.href = uri + base64(format(template, ctx));
compareLink.click();
}
</script>


<script>
    $(document).ready( function () {
        $('#table').DataTable({
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]]
        });
    } );
</script>

ChessTourManager.WEB/Views/Shared/_ExportPartial.cshtml
<p style="display: inline-block;">
    <button onclick="DownloadToExcel()" class="btn btn-primary">Download to Excel</button>
    <button onclick="Print()" class="btn btn-primary">Print</button>
</p>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://unpkg.com/xlsx/dist/xlsx.full.min.js"></script>

<script>

function Print() {
  var table = document.getElementById("table");
  var printWindow = window.open('');
  printWindow.document.write('<html><head><title>Print</title>');
  printWindow.document.write('</head><body >');

  var rows = table.rows;
  var ignoredColumns = [];

  for (var i = 0; i < rows.length; i++) {
    var cells = rows[i].querySelectorAll('th, td');
    for (var j = 0; j < cells.length; j++) {
      var cell = cells[j];
      if (cell.classList.contains('action-buttons')) {
        ignoredColumns.push(j);
        break; // Skip to the next row
      }
    }
  }

  var clonedTable = table.cloneNode(true);

  for (var i = 0; i < clonedTable.rows.length; i++) {
    var cells = clonedTable.rows[i].querySelectorAll('th, td');
    for (var j = cells.length - 1; j >= 0; j--) {
      if (ignoredColumns.includes(j)) {
        cells[j].remove();
      }
    }
  }

  printWindow.document.write(clonedTable.outerHTML);
  printWindow.document.write('</body></html>' +
    '<style type="text/css">' +
    'table th, table td {' +
    'border-bottom: 1px solid #000;' +
    'border-right: 1px solid #000;' +
    // center vertically and horizontally
    'text-align: center;' +
    'vertical-align: middle;' +
    '}' +
    '</style>');
  printWindow.document.close();

  printWindow.onafterprint = function () {
    printWindow.close();
  };

  printWindow.print();
}


function DownloadToExcel() {
  var table = $("#table");
  var headerCells = table.find("th");
  var headers = [];
  var columnIndexMap = {};

  headerCells.each(function (index) {
    var headerText = $(this).text().trim();
    if (headerText !== "") {
      headers.push(headerText);
      columnIndexMap[index] = headers.length - 1;
    }
  });

  var rows = table.find("tbody tr");
  var data = [];

  rows.each(function () {
    var rowData = [];
    var cells = $(this).find("td");

    cells.each(function (index) {
      var columnIndex = columnIndexMap[index];
      if (columnIndex !== undefined) {
        var cellContent = "";
        if ($(this).find("select").length > 0) {
          cellContent = $(this).find("select").val();
        } else {
          cellContent = $(this).text().trim();
        }
        rowData[columnIndex] = cellContent;
      }
    });

    if (rowData.length > 0) {
      data.push(rowData);
    }
  });

  var worksheet = XLSX.utils.aoa_to_sheet([headers].concat(data));
  var workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");
  var excelBuffer = XLSX.write(workbook, {
    bookType: "xlsx",
    type: "array",
    cellDates: true,
  });
  var blob = new Blob([excelBuffer], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });

  var link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "table.xlsx";
  link.click();
}

</script>

ChessTourManager.WEB/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] – ChessTourManager</title>
    <link rel="stylesheet" href="~/css/themes/bootswatch.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ChessTourManager.WEB.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChessTourManager</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area=""
                           asp-controller="Tournaments"
                           asp-action="Index">
                            Tournaments
                        </a>

                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        <partial name="_Notification"/>
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year – ChessTourManager – <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.js"></script>

@await RenderSectionAsync("Scripts", false)
</body>
</html>

ChessTourManager.WEB/Views/Shared/_Notification.cshtml
@if (TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]')
    </script>
}
@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
    </script>
}
@if (TempData["Warning"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.warning('@TempData["Warning"]')
    </script>
}

ChessTourManager.WEB/Views/Shared/_TournamentPartial.cshtml
@model ChessTourManager.DataAccess.Entities.Tournament
<h1>Tournament: @(Model?.TournamentName ?? string.Empty)</h1>
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border border-1 box-shadow mb-3">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                @if (ViewContext.RouteData.Values["controller"]?.ToString() == "Players")
                {
                    <li class="nav-item">
                        <a class="btn btn-primary text-light" asp-area="" asp-controller="Players" asp-action="Index" asp-route-id="@Model?.Id">Players</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index" asp-route-id="@Model?.Id">Players</a>
                    </li>
                }
                @if (Model.KindId != 1)
                {
                    @if (ViewContext.RouteData.Values["controller"]?.ToString() == "Teams")
                    {
                        <li class="nav-item">
                            <a class="btn btn-primary text-light" asp-area="" asp-controller="Teams" asp-action="Index" asp-route-id="@Model?.Id">Teams</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Index" asp-route-id="@Model?.Id">Teams</a>
                        </li>
                    }
                }
                @if (ViewContext.RouteData.Values["controller"]?.ToString() == "Groups")
                {
                    <li class="nav-item">
                        <a class="btn btn-primary text-light" asp-area="" asp-controller="Groups" asp-action="Index" asp-route-id="@Model?.Id">Groups</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index" asp-route-id="@Model?.Id">Groups</a>
                    </li>
                }
                @if (ViewContext.RouteData.Values["controller"]?.ToString() == "Games")
                {
                    <li class="nav-item">
                        <a class="btn btn-primary text-light" asp-area="" asp-controller="Games" asp-action="Index" asp-route-id="@Model?.Id">Games</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Games" asp-action="Index" asp-route-id="@Model?.Id">Games</a>
                    </li>
                }
                @if (ViewContext.RouteData.Values["controller"]?.ToString() == "Rating")
                {
                    <li class="nav-item">
                        <a class="btn btn-primary text-light" asp-area="" asp-controller="Rating" asp-action="Index" asp-route-id="@Model?.Id">Rating</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Rating" asp-action="Index" asp-route-id="@Model.Id">Rating</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>